### ISSUE TITLE
Add utc clock to telescope

### ISSUE THREAD

**Issue by centowen** [centowen/salsa#10]

**Comment by varenius** [comment]
Kan nog fixas genom att först i frontend/Cargo.toml lägga in dependency
`chrono = "0.4"`

sedan nånstans i rustkoden (oklart var för att detta ska uppdateras rätt senare) lägga in typ:
`let utcnow: DateTime<Utc> = Utc::now();`

och på rätt ställe i pages/telescope.rs:
```
                <div class="utcnow">
                    <h1>{utcnow.format("%Y-%m-%d %H:%M:%S")}</h1>
                </div>
```

**Comment by varenius** [comment]
Fast man kanske snarare, när jag tänker efter, vill ha en "Session time remaining" räknare som räknar ner från nu till slutet på nuvarande bokning. Då behöver man iofs också ha tiden nu, och tiden för bokningen (som finns i databas), så koden ovan är nog användbar ändå. Tror att tiden kvar bör visas i HH:MM:SS.

**Comment by varenius** [comment]
Superseeded by #21.
